language: python
python:
- 3.6
sudo: required
services:
- docker
install:
- pip install -r test-requirements.txt
- python setup.py develop
script:
- pytest cassettedeck/tests/ -x -s --log-cli-level=info
- flake8 cassettedeck --config=setup.cfg
after_success:
- codecov
- rm -rf *.egg-info
deploy:
  skip_cleanup: true
  #provider: pypi
  #user: ramon.nb
  #password:
  #  secure: abc
  on:
    tags: true
  distributions: sdist bdist_wheel
